### ISSUE TITLE
Error:Failed to resolve: com.lapism:searchview:3.0.2 

### ISSUE THREAD

**Issue by gincoo** [cuikangyuan/IT-eBook#1]
Error:Failed to resolve: com.lapism:searchview:3.0.2
<a href="openFile:D:/download/IT-eBook-master/IT-eBook-master/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by galihuotui** [comment]
i will check that tonight , thank you

**Comment by galihuotui** [comment]
那一个开源库可以在本地注释掉，是在项目中没有使用到的, 也可以update一下代码，我已更新push到最新

**Comment by benza86** [comment]
Failed to resolve: com.lapism:searchview:3.0.2
the same problem
any solution?

**Comment by benza86** [comment]
> 那一个开源库可以在本地注释掉，是在项目中没有使用到的, 也可以update一下代码，我已更新push到最新

can you exlain in english?
